### ISSUE TITLE
can you made this software works on windows 10?

### ISSUE THREAD

**Issue by kucing-kembar** [sam09/shot-detector#1]
hi, sorry for my bad English,
i get this page at py-scene-detect by you to author that page,
i have a little programming, but i never touch the Linux,
i tried "make" the software using gnuwin32 but the exe never appear,,
so my request is: please make it for windows 10 

my PC stats are:
-intel i5-4460
-GTX 750ti
-ram 8gb
-windows 10 64bit

optional: 
-for ffmpeg, i using this syntax to use nvidia GPU to process the data "-c:v h264_nvenc"
-as my experience in py-scene-detect, the threshold is different between each video, 
sometime you can cut into 2 or 4 scenes, other video sometimes cut into dozen scenes with same setting,
so can you make "2-part mode" : the video will cut into 2 parts using the highest threshold point,

thanks for reading, sorry if i rude or something, have a nice day

**Comment by kucing-kembar** [comment]
EDIT : after so many trial and error in this 6 hours, i give up, , this linux thing is confusing as hell,
please make the windows 10 for me:(

**Comment by sam09** [comment]
hi @kucing-kembar
I will try looking at this for windows. I do not have much experience with windows.

**Comment by kucing-kembar** [comment]
i really relieved that you answer my ridiculous request
thank you very very much

**Comment by kucing-kembar** [comment]
hi sam, it already a week, is there any progress?, just asking, no rush

**Comment by sam09** [comment]
Hi @kucing-kembar . I tried running it on a windows VM and it seems non trivial. I am sorry but at this moment, I just dont have the time to get it working for windows.

You can pick it up and try it out, but I am going to close this issue

**Comment by kucing-kembar** [comment]
sorry for late reply, and sorry if it out of topic
in 2008 or 2009, i tried Linux OS using flash drive as bootable (that years i using windows 7), then using the OS it without installing it, do you know what it call?
i like to try your code without installing Linux if it possible,
anyway what requirement to use your code?
any syntax to install it?

thanks for reading, and sorry if i rude
